# Generated by Django 4.0 on 2022-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_ishchilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishchilar',
            name='taym',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
