# Generated by Django 4.0.6 on 2022-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_ishchilar_taym'),
    ]

    operations = [
        migrations.CreateModel(
            name='murojatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
