# Generated by Django 4.0.6 on 2022-08-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_murojatlar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='maxsulotlar',
            new_name='Oyinlar',
        ),
    ]
