# Generated by Django 4.0.6 on 2022-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_rename_maxsulotlar_oyinlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=20)),
                ('emaili', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
