# Generated by Django 4.0.6 on 2022-09-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_kommentaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyinlar',
            name='silka',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
