# Generated by Django 4.0.6 on 2022-09-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_gmail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gmail',
        ),
    ]
