# Generated by Django 4.0.6 on 2022-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emails',
        ),
    ]
