# Generated by Django 4.0.6 on 2022-09-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='murojatlar',
            old_name='ism',
            new_name='ismis',
        ),
    ]
